[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-fft-core = { path = "../core" }
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
rand = "0.8.5"
